// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdiswbyszzkfjdumdivr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaXN3YnlzenprZmpkdW1kaXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5Mjg3OTYsImV4cCI6MjA1OTUwNDc5Nn0.bWEdvYHj9_CZxnHpcWvKfpZc6s4_AcONUalawL9srjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
